"""Fixed artifact names for one executable-report project root."""

SOURCE = "report.py"
NOTEBOOK = "report.executed.ipynb"
HTML = "report.rendered.html"
STATIC = "report.static"
INVENTORY = "report.inventory.json"
VERIFY_RECEIPT = "report.verify.json"
VERIFY_SCREENSHOT = "report.verify.png"
QUARTO_CONFIG = "_quarto.yml"
